### ISSUE TITLE
Training Code??

### ISSUE THREAD

**Issue by saifhasanr** [joonson/syncnet_python#64]
Thanks for the great work!!
Can you please provide the code for training the model.

**Comment by mc-marcocheng** [comment]
https://github.com/joonson/syncnet_trainer

**Comment by saifhasanr** [comment]
I have trained the model.
can anyone pls share the inference code

**Comment by joonson** [comment]
https://github.com/joonson/syncnet_trainer provides the implementation for "**Disentangled Speech Embeddings using Cross-Modal Self-Supervision**", whereas https://github.com/joonson/syncnet_python provides the inference code for "**Out of time: automated lip sync in the wild**", and they are not compatible. 

The training code for https://github.com/joonson/syncnet_python is not able to be released due to the age of the code, it should be fairly straightforward to reproduce based on the LRS3 dataset and the provided model files.
